### ISSUE TITLE
dealii installation

### ISSUE THREAD

**Issue by soumyadipghosh** [pratikvn/schwarz-lib#47]
In order to install dealii, do I simply follow the steps [here](https://dealii.org/9.1.1/readme.html)? Do I have to add any options for configuring with Ginkgo or anything else? Also, the docs specify compiling dealii in parallel, is that necessary?

**Comment by pratikvn** [comment]
Yes, I the installation docs of deal.ii should be the one to follow. I would suggest to install ginkgo first to some path, export that path to `Ginkgo_DIR` or some variable like that and during deal.ii compilation, add `DDEAL_II_WITH_GINKGO=on -DGINKGO_DIR=$Ginkgo_DIR` to the cmake command.

Yes, atleast according to what I faced, `-DDEAL_II_WITH_MPI` needed to be `on` because otherwise deal.ii would define some hooks for MPI variables such as `MPI_COMM_WORLD` which would mess up when you install schwarz-lib with MPI. Make sure that you install deal.ii, ginkgo and schwarz-lib with the same software stacks ( C,CXX compilers, MPI libraries, Cmake etc. ) otherwise you run into weird problems.

**Comment by soumyadipghosh** [comment]
Ok. What other options should I use, e.g - METIS, CUDA, etc ?

**Comment by pratikvn** [comment]
You can switch both off.
